server:
  port: 8080

db:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: bank_db

jwt:
  secret_key: your-secret-key
  expires_in: 24 # в часах

smtp:
  host: smtp.gmail.com
  port: 587
  username: your-email@gmail.com
  password: your-app-password
  from: your-email@gmail.com

card_private_key: "your-card-private-key-here"
card_public_key: "your-card-public-key-here"
card_hmac_key: "your-card-hmac-key-here" 